services:
  api:
    image: node:20-bullseye
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    command: bash -c "npm ci && npm start"
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      PORT: ${PORT}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
